theme = "term16_dark"

[editor]
line-number = "relative"
mouse = true
bufferline = "always"
rulers = [80, 100]
idle-timeout = 0

[editor.lsp]
auto-signature-help = false

[editor.whitespace]
render = "after-whitespace"
